; Untitled, Sound effects, format v2.0.

; Generated by Arkos Tracker 3.

BOOP_FXSoundEffects
BOOP_FXSoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
BOOP_FXSoundEffectsDisarkPointerRegionStart0
    dw BOOP_FXSoundEffects_Sound2    ; Sound effect 2 at index 1.
    dw BOOP_FXSoundEffects_Sound3    ; Sound effect 3 at index 2.
    dw BOOP_FXSoundEffects_Sound4    ; Sound effect 4 at index 3.
BOOP_FXSoundEffectsDisarkPointerRegionEnd0

BOOP_FXSoundEffectsDisarkByteRegionStart1
; Sound effect 2.
BOOP_FXSoundEffects_Sound2
    db 1    ; Speed

    db 57    ; Soft only. Volume: 14.
    dw 239    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 190    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 159    ; Software period.

    db 45    ; Soft only. Volume: 11.
    dw 119    ; Software period.

    db 37    ; Soft only. Volume: 9.
    dw 159    ; Software period.

    db 29    ; Soft only. Volume: 7.
    dw 119    ; Software period.

    db 17    ; Soft only. Volume: 4.
    dw 121    ; Software period.

    db 1    ; Soft only. Volume: 0.
    dw 239    ; Software period.

    db 4    ; End of the sound effect.

; Sound effect 3.
BOOP_FXSoundEffects_Sound3
    db 0    ; Speed

    db 61    ; Soft only. Volume: 15.
    dw 461    ; Software period.

    db 61    ; Soft only. Volume: 15.
    dw 458    ; Software period.

    db 57    ; Soft only. Volume: 14.
    dw 455    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 451    ; Software period.

    db 45    ; Soft only. Volume: 11.
    dw 446    ; Software period.

    db 181    ; Soft only. Volume: 13.
    db 8    ; Noise: 8.
    dw 453    ; Software period.

    db 169    ; Soft only. Volume: 10.
    db 10    ; Noise: 10.
    dw 451    ; Software period.

    db 157    ; Soft only. Volume: 7.
    db 12    ; Noise: 12.
    dw 451    ; Software period.

    db 145    ; Soft only. Volume: 4.
    db 14    ; Noise: 14.
    dw 451    ; Software period.

    db 1    ; Soft only. Volume: 0.
    dw 451    ; Software period.

    db 4    ; End of the sound effect.

; Sound effect 4.
BOOP_FXSoundEffects_Sound4
    db 0    ; Speed

    db 49    ; Soft only. Volume: 12.
    dw 338    ; Software period.

    db 29    ; Soft only. Volume: 7.
    dw 338    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 268    ; Software period.

    db 29    ; Soft only. Volume: 7.
    dw 268    ; Software period.

    db 57    ; Soft only. Volume: 14.
    dw 225    ; Software period.

    db 33    ; Soft only. Volume: 8.
    dw 225    ; Software period.

    db 45    ; Soft only. Volume: 11.
    dw 103    ; Software period.

    db 49    ; Soft only. Volume: 12.
    dw 171    ; Software period.

    db 53    ; Soft only. Volume: 13.
    dw 169    ; Software period.

    db 57    ; Soft only. Volume: 14.
    dw 335    ; Software period.

    db 61    ; Soft only. Volume: 15.
    dw 348    ; Software period.

    db 177    ; Soft only. Volume: 12.
    db 2    ; Noise: 2.
    dw 345    ; Software period.

    db 165    ; Soft only. Volume: 9.
    db 4    ; Noise: 4.
    dw 342    ; Software period.

    db 149    ; Soft only. Volume: 5.
    db 6    ; Noise: 6.
    dw 338    ; Software period.

    db 129    ; Soft only. Volume: 0.
    db 3    ; Noise: 3.
    dw 338    ; Software period.

    db 4    ; End of the sound effect.

BOOP_FXSoundEffectsDisarkByteRegionEnd1
