; Boop Menu Song 01, AKG format, v1.0.

; Generated by Arkos Tracker 3.

Start
StartDisarkGenerateExternalLabel

DisarkByteRegionStart0
    db "AT30"
DisarkPointerRegionStart1
    dw ArpeggioTable    ; The address of the Arpeggio table.
    dw PitchTable    ; The address of the Pitch table.
    dw InstrumentTable    ; The address of the Instrument table.
    dw EffectBlockTable    ; The address of the Effect Block table.
DisarkPointerRegionEnd1


; The addresses of each Subsong.
DisarkPointerRegionStart2
    dw Subsong0_Start
    dw Subsong1_Start
    dw Subsong2_Start
    dw Subsong3_Start
DisarkPointerRegionEnd2

; Declares all the Arpeggios.
ArpeggioTable
DisarkPointerRegionStart3
DisarkPointerRegionEnd3

; Declares all the Pitches.
PitchTable
DisarkPointerRegionStart4
DisarkPointerRegionEnd4

; Declares all the Instruments.
InstrumentTable
DisarkPointerRegionStart5
    dw EmptyInstrument
    dw Instrument1
    dw Instrument2
    dw Instrument3
    dw Instrument4
    dw Instrument5
    dw Instrument6
DisarkPointerRegionEnd5

EmptyInstrument
    db 0    ; The speed (>0, 0 for 256).

    db 0    ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

Instrument1
    db 1    ; The speed (>0, 0 for 256).

    db 249    ; Soft only. Volume: 15. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 6    ; Loop to silence.

Instrument2
    db 1    ; The speed (>0, 0 for 256).

    db 121    ; Soft only. Volume: 15.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -3    ; Pitch.

    db 113    ; Soft only. Volume: 14.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -1    ; Pitch.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 81    ; Soft only. Volume: 10.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -1    ; Pitch.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 81    ; Soft only. Volume: 10.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw 1    ; Pitch.

    db 6    ; Loop to silence.

Instrument3
    db 1    ; The speed (>0, 0 for 256).

    db 225    ; Soft only. Volume: 12. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 17    ; Soft only. Volume: 2.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw 1    ; Pitch.

    db 6    ; Loop to silence.

Instrument4
    db 1    ; The speed (>0, 0 for 256).

    db 121    ; Soft only. Volume: 15.
    db 37    ; Additional data. Noise: 5. Pitch? true. Arp? false. Period? false.
    dw 6    ; Pitch.

    db 113    ; Soft only. Volume: 14.
    db 40    ; Additional data. Noise: 8. Pitch? true. Arp? false. Period? false.
    dw 4    ; Pitch.

    db 105    ; Soft only. Volume: 13.
    db 42    ; Additional data. Noise: 10. Pitch? true. Arp? false. Period? false.
    dw 2    ; Pitch.

    db 89    ; Soft only. Volume: 11.
    db 12    ; Additional data. Noise: 12. Pitch? false. Arp? false. Period? false.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 6    ; Loop to silence.

Instrument5
    db 1    ; The speed (>0, 0 for 256).

    db 233    ; Soft only. Volume: 13. Volume only.

    db 89    ; Soft only. Volume: 11.
    db 64    ; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    db 12    ; Arpeggio.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 57    ; Soft only. Volume: 7.
    db 64    ; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    db 12    ; Arpeggio.

    db 49    ; Soft only. Volume: 6.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw 1    ; Pitch.

    db 33    ; Soft only. Volume: 4.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw 2    ; Pitch.

    db 17    ; Soft only. Volume: 2.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw 3    ; Pitch.

    db 6    ; Loop to silence.

Instrument6
    db 1    ; The speed (>0, 0 for 256).

    db 121    ; Soft only. Volume: 15.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -3    ; Pitch.

    db 113    ; Soft only. Volume: 14.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -2    ; Pitch.

    db 105    ; Soft only. Volume: 13.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -1    ; Pitch.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 73    ; Soft only. Volume: 9.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -1    ; Pitch.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 73    ; Soft only. Volume: 9.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw 1    ; Pitch.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 73    ; Soft only. Volume: 9.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -1    ; Pitch.

    db 6    ; Loop to silence.


; The indexes of the effect blocks used by this song.
EffectBlockTable
DisarkPointerRegionStart6
    dw EffectBlock_P4P2    ; Index 0
    dw EffectBlock_P4P1    ; Index 1
    dw EffectBlock_P4P0    ; Index 2
DisarkPointerRegionEnd6
EffectBlock_P4P1
    db 4
    db 1

EffectBlock_P4P2
    db 4
    db 2

EffectBlock_P4P0
    db 4
    db 0


DisarkByteRegionEnd0
